default_context:
  project_name: 'nightmare_server'
  project_slug: 'nightmare_server'
  domain_main: 'nightmare.fun'
  domain_staging: 'nightmare.fun'
  docker_swarm_stack_name_main: 'nightmare-fun'
  docker_swarm_stack_name_staging: 'nightmare-fun'
  secret_key: 'df72fd8adb7fbbd0a03ef3842399569bd346a2d763d6cd7922527cf63df0759c'
  first_superuser: 'admin@nightmare.fun'
  first_superuser_password: '0c09c9df0604ccb92d907ec7b47acecb3fa0d33cf669bd4c63ddf10ace19ea2c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.nightmare.fun", "https://nightmare.fun", "https://nightmare.fun", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@nightmare.fun'
  postgres_password: 'mys906262255'
  pgadmin_default_user: 'admin@nightmare.fun'
  pgadmin_default_user_password: 'mys906262255'
  traefik_constraint_tag: 'nightmare.fun'
  traefik_constraint_tag_staging: 'nightmare.fun'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:0c09c9df0604ccb92d907ec7b47acecb3fa0d33cf669bd4c63ddf10ace19ea2c'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
